# Generated by Django 2.2.6 on 2019-11-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='userImg',
            field=models.ImageField(default='/car_pictures/default.jpg', upload_to='user_avas/'),
        ),
    ]
