# Generated by Django 2.2.6 on 2019-12-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0002_auto_20191128_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='city_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ourApp.City'),
        ),
    ]
