# Generated by Django 2.2.6 on 2019-12-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0003_auto_20191202_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('card_numbers', models.CharField(max_length=200)),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='expiration date')),
                ('cvv_code', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_picture', models.ImageField(default='NULL', upload_to='license_pictures/')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='bank_card_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ourApp.BankCard'),
        ),
        migrations.AddField(
            model_name='car',
            name='license_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ourApp.DriverLicense'),
        ),
    ]
