# Generated by Django 2.2.6 on 2019-11-13 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0003_engine_fueltype_gallery_modelofcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='starting date')),
                ('end_date', models.DateTimeField(verbose_name='ending date')),
                ('approves', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('canceled', models.BooleanField()),
                ('total_price', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('car_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ourApp.Car')),
            ],
        ),
    ]
