# Generated by Django 2.2.6 on 2019-12-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0004_auto_20191202_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='bank_card_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='license_id',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='bank_card_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourApp.BankCard'),
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='license_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourApp.DriverLicense'),
        ),
    ]
