# Generated by Django 2.2.6 on 2019-11-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourApp.Engine'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourApp.FuelType'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourApp.ModelOfCar'),
        ),
        migrations.AddField(
            model_name='car',
            name='picture_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourApp.Gallery'),
        ),
    ]
