# Generated by Django 2.2.6 on 2019-12-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0004_auto_20191208_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
