# Generated by Django 2.2.6 on 2019-12-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0005_auto_20191208_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
    ]
