# Generated by Django 2.2.6 on 2019-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0006_auto_20191209_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='desciption_text',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
