# Generated by Django 2.2.6 on 2019-12-02 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_card_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ourApp.BankCard'),
        ),
        migrations.AddField(
            model_name='order',
            name='license_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ourApp.DriverLicense'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
