# Generated by Django 2.2.6 on 2019-11-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0006_additionalequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='add_equip_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourApp.AdditionalEquipment'),
        ),
    ]
