# Generated by Django 2.2.6 on 2019-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0007_car_desciption_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='ending date'),
        ),
        migrations.AlterField(
            model_name='car',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='starting date'),
        ),
    ]
