# Generated by Django 2.2.6 on 2019-12-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0007_auto_20191202_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.AddField(
            model_name='car',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ending date'),
        ),
        migrations.AddField(
            model_name='car',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='starting date'),
        ),
    ]
