# Generated by Django 2.2.6 on 2019-12-09 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0009_auto_20191210_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ourApp.Car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
