# Generated by Django 2.2.6 on 2019-12-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0009_auto_20191208_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='bankcard',
            name='expiration_month',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='expiration_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_numbers',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='cvv_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='full_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(max_length=200),
        ),
    ]
