# Generated by Django 2.2.6 on 2019-12-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0011_auto_20191208_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank_card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourApp.BankCard'),
        ),
        migrations.AlterField(
            model_name='order',
            name='license_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourApp.DriverLicense'),
        ),
    ]
