# Generated by Django 2.2.6 on 2019-12-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0011_auto_20191210_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email_address',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
