# Generated by Django 2.2.6 on 2019-12-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourApp', '0013_auto_20191208_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='bank_card_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ourApp.BankCard'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='license_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ourApp.DriverLicense'),
        ),
    ]
